"""agent-policy-gateway: policy enforcement and IFC for AI agent tool calls."""

from agent_policy_gateway.anthropic_adapter import (
    AnthropicTool,
    AnthropicToolUseError,
    anthropic_tool_specs,
    dispatch_anthropic_tool_use,
    dispatch_anthropic_tool_uses,
    wrap_anthropic_tools,
)
from agent_policy_gateway.audit import (
    GENESIS_PREV,
    AuditFormatError,
    AuditRecord,
    ChainVerifyResult,
    JsonlAuditWriter,
    format_record,
    read_audit,
    replay_main,
    verify_chain,
)
from agent_policy_gateway.bench import (
    BenchResult,
    bench_main,
    benchmark,
    format_results_table,
    results_to_json,
    run_default_suite,
)
from agent_policy_gateway.cli import main as cli_main
from agent_policy_gateway.core import (
    Decision,
    Provenance,
    ProvenanceEntry,
    TaintLabel,
    ToolCall,
    Verdict,
    from_json,
    to_json,
)
from agent_policy_gateway.gateway import (
    AGENT_ID_KWARG,
    CALL_ID_KWARG,
    INPUT_LABEL_KWARG,
    PROVENANCE_KWARG,
    RESOURCE_KWARG,
    AuditWriter,
    Gateway,
    GatewayError,
    PolicyDenied,
    PolicyReview,
)
from agent_policy_gateway.langchain_adapter import wrap_langchain_tools
from agent_policy_gateway.mcp_adapter import wrap_mcp_session
from agent_policy_gateway.mcp_async_adapter import wrap_mcp_session_async
from agent_policy_gateway.openai_adapter import (
    OpenAITool,
    OpenAIToolCallError,
    dispatch_openai_tool_call,
    dispatch_openai_tool_calls,
    openai_tool_specs,
    wrap_openai_tools,
)
from agent_policy_gateway.policy import (
    Action,
    Effect,
    Policy,
    PolicyError,
    RedactSpec,
    Rule,
    Selector,
    TaintCondition,
    load_policies,
    load_policy,
    load_policy_str,
)
from agent_policy_gateway.ratelimit import DEFAULT_WINDOW_SECONDS, RateLimiter
from agent_policy_gateway.reload import (
    WatchedPolicy,
    watch_policy,
)
from agent_policy_gateway.taint import (
    ToolTaintSpec,
    flows_to,
    join,
    join_all,
    propagate,
    propagate_provenance,
    subsumes,
)

__version__ = "0.0.1"

__all__ = [
    "AGENT_ID_KWARG",
    "Action",
    "AnthropicTool",
    "AnthropicToolUseError",
    "AuditFormatError",
    "AuditRecord",
    "ChainVerifyResult",
    "GENESIS_PREV",
    "AuditWriter",
    "BenchResult",
    "CALL_ID_KWARG",
    "Decision",
    "Effect",
    "Gateway",
    "GatewayError",
    "INPUT_LABEL_KWARG",
    "JsonlAuditWriter",
    "OpenAITool",
    "OpenAIToolCallError",
    "Policy",
    "PolicyDenied",
    "PolicyError",
    "PolicyReview",
    "PROVENANCE_KWARG",
    "Provenance",
    "ProvenanceEntry",
    "DEFAULT_WINDOW_SECONDS",
    "RESOURCE_KWARG",
    "RateLimiter",
    "RedactSpec",
    "Rule",
    "Selector",
    "TaintCondition",
    "TaintLabel",
    "ToolCall",
    "ToolTaintSpec",
    "Verdict",
    "WatchedPolicy",
    "__version__",
    "anthropic_tool_specs",
    "bench_main",
    "cli_main",
    "benchmark",
    "dispatch_anthropic_tool_use",
    "dispatch_anthropic_tool_uses",
    "dispatch_openai_tool_call",
    "dispatch_openai_tool_calls",
    "flows_to",
    "format_record",
    "format_results_table",
    "from_json",
    "join",
    "join_all",
    "load_policies",
    "load_policy",
    "load_policy_str",
    "openai_tool_specs",
    "propagate",
    "propagate_provenance",
    "read_audit",
    "replay_main",
    "verify_chain",
    "results_to_json",
    "run_default_suite",
    "subsumes",
    "to_json",
    "wrap_anthropic_tools",
    "wrap_langchain_tools",
    "wrap_mcp_session",
    "wrap_mcp_session_async",
    "watch_policy",
    "wrap_openai_tools",
]
